import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { notFound } from "next/navigation";
import "../../../../styles/globals.scss";
import { ApolloWrapper } from "@/lib/graphql/apolloClient";
import { Navbar } from "@/components/Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ["en", "pt-BR"] as const;

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  if (!locales.includes(locale as (typeof locales)[number])) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={montserrat.variable}>
        <Navbar locale={locale} />
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
